### ISSUE TITLE
Rust image /node_modules/ws/lib/websocket.js:347SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by thijndehaas** [pterodactyl/images#48]
All my servers that start with the latest Rust image give a crash. This error was not in the panel yesterday. Is there a way to downgrade the image or somehow fix this?

```Starting Rust...
/node_modules/ws/lib/websocket.js:347
...options
^^^
SyntaxError: Unexpected token ...
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/node_modules/ws/index.js:3:19)
[Pterodactyl Daemon] Server marked as OFF```

**Comment by parkervcp** [comment]
What image are you using to run your server?

**Comment by thijndehaas** [comment]
quay.io/pterodactyl/core:rust

**Comment by thijndehaas** [comment]
I just tried to create a server with the Ark egg and this seems to work fine. When a new Rust server was created I found out the problem. I just rebuild the container of an existing Rust server and it resulted in the same error.

**Comment by JKJameson** [comment]
Same issue. There are random "..." in the websocket.js script that shouldn't be there. Whoops! :)

**Comment by parkervcp** [comment]
There are no `...` in the wrapper.js except for the waiting for rcon and updating umod messages.

**Comment by DaneEveritt** [comment]
The "random" `...` is actually valid [JS spread operator syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) but thats only in ES6.

**Comment by parkervcp** [comment]
It's built now so this should be fixed.

**Comment by Pedroxam** [comment]
Not fixed. i have same problem

**Comment by parkervcp** [comment]
I feel like I need to call out this - https://github.com/pterodactyl/images/pull/55

Also feel like you guys need to look before you comment.

**Comment by JKJameson** [comment]
That's all fine and well, but this is #48 if you have that attitude.

**Comment by Pedroxam** [comment]
@parkervcp, i reinstall nodejs and now everything is ok.
