### ISSUE TITLE
New docker image with Java 13 ShenandoahGC ready.

### ISSUE THREAD

**Issue by SrBedrock** [pterodactyl/images#57]
Hi guys, thanks for this open source project!
Very well documented, even without understanding linux I was able to install my panel easily.

I'm hosting Minecraft 1.15.2 and apparently the use of garbage collectors like ShenandoahGC has proven to be superior to G1GC in this version.

After several searches I found that unfortunately the java version made available by Oracle (openjdk 11, 12 and 13) does not come with the option enabled.

[The reason is explained here.](https://developers.redhat.com/blog/2019/04/19/not-all-openjdk-12-builds-include-shenandoah-heres-why/).

[Project page with all relevant information ](https://wiki.openjdk.java.net/display/shenandoah/Main#Main-JDKSupport)

Could you help me install a compatible docker image?

I really tried to create a dockerfile but due to lack of knowledge I couldn't.

[I was trying to install this java 13 which is compatible according to the project instructions.](https://hub.docker.com/layers/shipilev/openjdk/13/images/sha256-baaa3135aebfcd524ebf0dd06201f1c3c518ed9d751196547e074440b52cc8cd?context=explore)

Thanks guys!

**Comment by parkervcp** [comment]
I would have made this issue for my repo and not the main images repo

**Comment by SrBedrock** [comment]
Should I do something about the issue? Should I close it?

**Comment by parkervcp** [comment]
I'll close this one. Open a request on my fork please.

**Comment by SrBedrock** [comment]
[I opened a new issue in the right place.](https://github.com/parkervcp/images/issues/38)
