### ISSUE TITLE
Rust Image has incorrect steam cmd path.

### ISSUE THREAD

**Issue by Soccerjunki** [pterodactyl/images#64]
Panel Version: 1.0.2
Daemon Version: 1.0.1
Service: Rust
Docker Image: quay.io/pterodactyl/core:rust
Modified: no

Errors that you are experiencing: 

Rust servers won't automatically update on restart anymore, because it's looking for the steamcmd.sh in the wrong folder. The steamcmd.sh file is located in steam/steamcmd.sh instead it's searching for it, in the steamcmd directory.

**Comment by parkervcp** [comment]
This should be fixed at the install script end then.

**Comment by Soccerjunki** [comment]
Ignore this ticket i'm stupid, turns out the install script was updated.
