### ISSUE TITLE
Java 11/16 OpenJ9

### ISSUE THREAD

**Issue by Korrivyn** [pterodactyl/images#77]
I'm not as familiar with images however I'd like to mention that while we have a JDK 11 now, I'd love to see the use of OpenJ9 based on the issue that was opened before regarding it for JDK 8. (Opened on the main panel issues, but still)

https://github.com/pterodactyl/panel/issues/1646

Furthermore, I suppose I should mention that a JDK 16 is around with OpenJ9 as well which would be excellent to have for the base images to select from. Thanks for the great work, and my apologies I'm not familiar enough with images to make one up myself and submit it haha

**Comment by trenutoo** [comment]
Parker has the openjdk11/openj9 Docker image on [his repository](https://github.com/parkervcp/images/tree/debian/openjdk-11-openj9), which you can also use with `quay.io/parkervcp/pterodactyl-images:debian_openjdk-11-openj9`

I also have images for Java 11/16 openj9 [here.](https://github.com/Software-Noob/pterodactyl-images)

**ED:** This has now been resolved with the introduction of [Pterodactyl Yolks.](https://github.com/pterodactyl/yolks)

**Comment by TjeuKayim** [comment]
Having an openjdk-16 image is also important for PaperMC, see https://github.com/parkervcp/eggs/pull/1147. The minimum Java version will be 16 in the upcoming release this summer. Please include a `java-16` image to be used in  [`egg-paper.json`](https://github.com/pterodactyl/panel/blob/develop/database/Seeders/eggs/minecraft/egg-paper.json).

**Comment by trenutoo** [comment]
This has now been resolved with the introduction of [Pterodactyl Yolks.](https://github.com/pterodactyl/yolks)
