### ISSUE TITLE
Possible entrypoint.sh issue with base_ubuntu

### ISSUE THREAD

**Issue by lifewcody** [pterodactyl/images#81]
Hello,

Specifically, I was referring to: https://github.com/parkervcp/eggs/tree/master/game_eggs/minetest/minetest

Which references the docker container: quay.io\/parkervcp\/pterodactyl-images:base_ubuntu

Which I believe is referenced from: https://github.com/pterodactyl/images

So anywho, when using the base_ubuntu image, none of the variables come over. When modifying the startup command in pterodactyl, ex: {{SERVER_PORT}} it does not translate over. I believe it has to do with the entrypoint.sh (specifically using exec instead of just ${MODIFIED_STARTUP}).

Using the java one for Minecraft works just fine.

**Comment by trenutoo** [comment]
Base ubuntu image is on parkers repository, not this one
