### ISSUE TITLE
E: Unable to locate package sqlite

### ISSUE THREAD

**Issue by andris155** [pterodactyl/images#83]
Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: v1.5.1
Daemon Version: v1.4.7
Service: Minecraft
Docker Image: java-16
Modified: no

Errors that you are experiencing:
The Docker container build not work. Writes this error: E: Unable to locate package sqlite

**Comment by trenutoo** [comment]
What do you mean by building the container fails? The java 16 image from this repository is not built anywhere. We have moved to using [yolks](https://github.com/pterodactyl/yolks)
