### ISSUE TITLE
Umod/Oxide Download broken in rust:core

### ISSUE THREAD

**Issue by recon88** [pterodactyl/images#85]
The Umod site seems to have updated and is now using Cloudflare and/or being attacked so the file isn't reachable.
My Pterodactyl instance is unable to donwload the zip file containing Umod/Oxide for Rust.

```
Updating uMod...
[umod.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of umod.zip or
        umod.zip.zip, and cannot find umod.zip.ZIP, period.
```

Could you please exchange the links in `entrypoint.sh` on `quay.io/pterodactyl/core:rust`?

`https://umod.org/games/rust/download/develop`
->
`https://github.com/OxideMod/Oxide.Rust/releases/latest/download/Oxide.Rust-linux.zip`

The link on the page is basically just a redirect to the latest Github Release. Might as well just use that to make it work again.

**Comment by iamkubi** [comment]
PR already sent for it https://github.com/parkervcp/images/pull/98

**Comment by trenutoo** [comment]
> PR already sent for it https://github.com/parkervcp/images/pull/98

That's a fork which is the wrong place for a PR
